module.exports = {
  CATEGORY_CREATE: "CATEGORY_CREATE",
  CATEGORY_SWITCH: "CATEGORY_SWITCH",
  CATEGORY_TITLE_UPDATE: "CATEGORY_TITLE_UPDATE",
  CATEGORY_ORDERBY_UPDATE: "CATEGORY_ORDERBY_UPDATE",
  CATEGORY_ORDER_UPDATE: "CATEGORY_ORDER_UPDATE",
  CATEGORY_DESTROY: "CATEGORY_DESTROY",
  CATEGORY_ALLID: "CATEGORY_ALLID"
};
