module.exports = {
  HEADER_SEARCH: "HEADER_SEARCH",
  HEADER_UPDATE_ORDERBY: "HEADER_UPDATE_ORDERBY",
  HEADER_UPDATE_FILTER: "HEADER_UPDATE_FILTER",
  HEADER_FILTER_CURRENT: "HEADER_FILTER_CURRENT",
  HEADER_FILTER_ALL: "HEADER_FILTER_ALL",
  HEADER_FILTER_COMPLETED: "HEADER_FILTER_COMPLETED"
};
