module.exports = {
  MISSION_CREATE: "MISSION_CREATE",
  MISSION_EDITING: "MISSION_EDITING",
  MISSION_DESTROY: "MISSION_DESTROY",
  MISSION_UPDATE: "MISSION_UPDATE",
  MISSION_UPDATE_MISSION: "MISSION_UPDATE_MISSION",
  MISSION_DESTROY_BY_CATEGORY: "MISSION_DESTROY_BY_CATEGORY"
};
